// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/risingwavelabs/eventapi/app"
	"github.com/risingwavelabs/eventapi/pkg/closer"
	"github.com/risingwavelabs/eventapi/pkg/config"
	"github.com/risingwavelabs/eventapi/pkg/gctx"
	"github.com/risingwavelabs/eventapi/pkg/logger"
	"github.com/risingwavelabs/eventapi/pkg/rw"
)

// Injectors from wire.go:

func InitApp() (*app.App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	zapLogger, err := logger.NewLogger()
	if err != nil {
		return nil, err
	}
	globalContext := gctx.New(zapLogger)
	closerManager := closer.NewCloserManager(zapLogger)
	bulkInsertManager, err := rw.NewBulkInsertManager(globalContext, closerManager, zapLogger)
	if err != nil {
		return nil, err
	}
	risingWave, err := rw.NewRisingWave(configConfig, globalContext, bulkInsertManager, closerManager)
	if err != nil {
		return nil, err
	}
	serverInterface := app.NewHandler(risingWave)
	appApp := app.NewApp(configConfig, globalContext, zapLogger, serverInterface)
	return appApp, nil
}
