// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/risingwavelabs/events-api/app"
	"github.com/risingwavelabs/events-api/pkg/closer"
	"github.com/risingwavelabs/events-api/pkg/config"
	"github.com/risingwavelabs/events-api/pkg/gctx"
	"github.com/risingwavelabs/events-api/pkg/logger"
	"github.com/risingwavelabs/events-api/pkg/rw"
)

// Injectors from wire.go:

func InitApp() (*app.App, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	zapLogger, err := logger.NewLogger()
	if err != nil {
		return nil, err
	}
	globalContext := gctx.New(zapLogger)
	closerManager := closer.NewCloserManager(zapLogger)
	risingWave, err := rw.NewRisingWave(configConfig, globalContext, closerManager, zapLogger)
	if err != nil {
		return nil, err
	}
	bulkInsertManager, err := rw.NewBulkInsertManager(globalContext, risingWave, closerManager, zapLogger)
	if err != nil {
		return nil, err
	}
	eventService, err := rw.NewEventService(globalContext, risingWave, zapLogger, bulkInsertManager)
	if err != nil {
		return nil, err
	}
	serverInterface := app.NewHandler(risingWave, eventService)
	appApp := app.NewApp(configConfig, globalContext, zapLogger, serverInterface)
	return appApp, nil
}
