openapi: 3.0.0

info:
  title: Event API
  version: "1.0"
  description: API for real-time events

servers:
  - url: /v1
    description: Base API path

paths:
  /events:
    post:
      summary: Ingest a new event
      operationId: ingestEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Event ingested successfully
